/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Hypertable.ThriftGen
{

  [Serializable]
  public partial class AccessGroup : TBase
  {
    private string _name;
    private bool _in_memory;
    private short _replication;
    private int _blocksize;
    private string _compressor;
    private string _bloom_filter;
    private List<ColumnFamily> _columns;

    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        __isset.name = true;
        this._name = value;
      }
    }

    public bool In_memory
    {
      get
      {
        return _in_memory;
      }
      set
      {
        __isset.in_memory = true;
        this._in_memory = value;
      }
    }

    public short Replication
    {
      get
      {
        return _replication;
      }
      set
      {
        __isset.replication = true;
        this._replication = value;
      }
    }

    public int Blocksize
    {
      get
      {
        return _blocksize;
      }
      set
      {
        __isset.blocksize = true;
        this._blocksize = value;
      }
    }

    public string Compressor
    {
      get
      {
        return _compressor;
      }
      set
      {
        __isset.compressor = true;
        this._compressor = value;
      }
    }

    public string Bloom_filter
    {
      get
      {
        return _bloom_filter;
      }
      set
      {
        __isset.bloom_filter = true;
        this._bloom_filter = value;
      }
    }

    public List<ColumnFamily> Columns
    {
      get
      {
        return _columns;
      }
      set
      {
        __isset.columns = true;
        this._columns = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool name;
      public bool in_memory;
      public bool replication;
      public bool blocksize;
      public bool compressor;
      public bool bloom_filter;
      public bool columns;
    }

    public AccessGroup() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Name = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              In_memory = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I16) {
              Replication = iprot.ReadI16();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              Blocksize = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Compressor = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              Bloom_filter = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.List) {
              {
                Columns = new List<ColumnFamily>();
                TList _list28 = iprot.ReadListBegin();
                for( int _i29 = 0; _i29 < _list28.Count; ++_i29)
                {
                  ColumnFamily _elem30 = new ColumnFamily();
                  _elem30 = new ColumnFamily();
                  _elem30.Read(iprot);
                  Columns.Add(_elem30);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AccessGroup");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Name != null && __isset.name) {
        field.Name = "name";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Name);
        oprot.WriteFieldEnd();
      }
      if (__isset.in_memory) {
        field.Name = "in_memory";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(In_memory);
        oprot.WriteFieldEnd();
      }
      if (__isset.replication) {
        field.Name = "replication";
        field.Type = TType.I16;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI16(Replication);
        oprot.WriteFieldEnd();
      }
      if (__isset.blocksize) {
        field.Name = "blocksize";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Blocksize);
        oprot.WriteFieldEnd();
      }
      if (Compressor != null && __isset.compressor) {
        field.Name = "compressor";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Compressor);
        oprot.WriteFieldEnd();
      }
      if (Bloom_filter != null && __isset.bloom_filter) {
        field.Name = "bloom_filter";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Bloom_filter);
        oprot.WriteFieldEnd();
      }
      if (Columns != null && __isset.columns) {
        field.Name = "columns";
        field.Type = TType.List;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Columns.Count));
          foreach (ColumnFamily _iter31 in Columns)
          {
            _iter31.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AccessGroup(");
      sb.Append("Name: ");
      sb.Append(Name);
      sb.Append(",In_memory: ");
      sb.Append(In_memory);
      sb.Append(",Replication: ");
      sb.Append(Replication);
      sb.Append(",Blocksize: ");
      sb.Append(Blocksize);
      sb.Append(",Compressor: ");
      sb.Append(Compressor);
      sb.Append(",Bloom_filter: ");
      sb.Append(Bloom_filter);
      sb.Append(",Columns: ");
      sb.Append(Columns);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
