/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hypertable.ThriftGen
{
  public enum ColumnPredicateOperation
  {
    EXACT_MATCH = 1,
    PREFIX_MATCH = 2,
  }
}
