/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Hypertable.ThriftGen
{
  public enum MutatorFlag
  {
    NO_LOG_SYNC = 1,
    IGNORE_UNKNOWN_CFS = 2,
  }
}
